/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.padaria.view;

import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JPasswordField;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author W
 */
public class CadastroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CadastroUsuario
     */
    public CadastroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblendereco = new javax.swing.JLabel();
        enviar = new javax.swing.JButton();
        endereco = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cancelar = new javax.swing.JButton();
        sexo = new javax.swing.JComboBox<>();
        lblsexo = new javax.swing.JLabel();
        telefone = new javax.swing.JFormattedTextField();
        lbltelefone = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        cep = new javax.swing.JFormattedTextField();
        lblemail = new javax.swing.JLabel();
        lblcep = new javax.swing.JLabel();
        senha = new javax.swing.JPasswordField();
        nascimento = new javax.swing.JFormattedTextField();
        lblnascimento = new javax.swing.JLabel();
        cpf = new javax.swing.JFormattedTextField();
        lblsenha = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        usuario = new javax.swing.JTextField();
        lblcpf = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lblnome = new javax.swing.JLabel();
        lblcadastrese = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblendereco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblendereco.setText("ENDEREÇO:");
        getContentPane().add(lblendereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, -1, -1));

        enviar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enviar.setText("Cadastrar");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });
        getContentPane().add(enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 170, 30));

        endereco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        endereco.setViewportView(jTextArea1);

        getContentPane().add(endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 160, -1));

        cancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancelar.setText("Cancelar");
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, 170, 30));

        sexo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sexo", "Masculino", "Feminino" }));
        getContentPane().add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 160, 30));

        lblsexo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblsexo.setText("SEXO:");
        getContentPane().add(lblsexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, -1));

        try {
            telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 160, 30));

        lbltelefone.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbltelefone.setText("TELEFONE:");
        getContentPane().add(lbltelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 130, -1));

        email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 160, 30));

        try {
            cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cep.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(cep, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 180, 30));

        lblemail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblemail.setText("E-MAIL:");
        getContentPane().add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        lblcep.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblcep.setText("CEP:");
        getContentPane().add(lblcep, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));

        senha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 180, 30));

        try {
            nascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        nascimento.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(nascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 180, 30));

        lblnascimento.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblnascimento.setText("Nascimento:");
        getContentPane().add(lblnascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        try {
            cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpf.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 180, 30));

        lblsenha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblsenha.setText("Senha:");
        getContentPane().add(lblsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 80, 30));

        nome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 180, 30));

        usuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 180, 30));

        lblcpf.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblcpf.setText("CPF:");
        getContentPane().add(lblcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        lblusuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblusuario.setText("Usuário:");
        getContentPane().add(lblusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 90, 40));

        lblnome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblnome.setText("Nome:");
        getContentPane().add(lblnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 70, 30));

        lblcadastrese.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        lblcadastrese.setForeground(new java.awt.Color(255, 255, 255));
        lblcadastrese.setText("Cadastre-se");
        getContentPane().add(lblcadastrese, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        background.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/padaria/imagens/telaCadastro.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        
    }//GEN-LAST:event_enviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton cancelar;
    private javax.swing.JFormattedTextField cep;
    private javax.swing.JFormattedTextField cpf;
    private javax.swing.JTextField email;
    private javax.swing.JScrollPane endereco;
    private javax.swing.JButton enviar;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblcadastrese;
    private javax.swing.JLabel lblcep;
    private javax.swing.JLabel lblcpf;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblendereco;
    private javax.swing.JLabel lblnascimento;
    private javax.swing.JLabel lblnome;
    private javax.swing.JLabel lblsenha;
    private javax.swing.JLabel lblsexo;
    private javax.swing.JLabel lbltelefone;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JFormattedTextField nascimento;
    private javax.swing.JTextField nome;
    private javax.swing.JPasswordField senha;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JFormattedTextField telefone;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables

    public JButton getCancelar() {
        return cancelar;
    }

    public void setCancelar(JButton cancelar) {
        this.cancelar = cancelar;
    }

    public JFormattedTextField getCep() {
        return cep;
    }

    public void setCep(JFormattedTextField cep) {
        this.cep = cep;
    }

    public JFormattedTextField getCpf() {
        return cpf;
    }

    public void setCpf(JFormattedTextField cpf) {
        this.cpf = cpf;
    }

    public JTextField getEmail() {
        return email;
    }

    public void setEmail(JTextField email) {
        this.email = email;
    }

    public JScrollPane getEndereco() {
        return endereco;
    }

    public void setEndereco(JScrollPane endereco) {
        this.endereco = endereco;
    }

    public JButton getEnviar() {
        return enviar;
    }

    public void setEnviar(JButton enviar) {
        this.enviar = enviar;
    }

    public JTextArea getjTextArea1() {
        return jTextArea1;
    }

    public void setjTextArea1(JTextArea jTextArea1) {
        this.jTextArea1 = jTextArea1;
    }

    public JFormattedTextField getNascimento() {
        return nascimento;
    }

    public void setNascimento(JFormattedTextField nascimento) {
        this.nascimento = nascimento;
    }

    public JTextField getNome() {
        return nome;
    }

    public void setNome(JTextField nome) {
        this.nome = nome;
    }

    public JPasswordField getSenha() {
        return senha;
    }

    public void setSenha(JPasswordField senha) {
        this.senha = senha;
    }

    public JFormattedTextField getTelefone() {
        return telefone;
    }

    public void setTelefone(JFormattedTextField telefone) {
        this.telefone = telefone;
    }

    public JTextField getUsuario() {
        return usuario;
    }

    public void setUsuario(JTextField usuario) {
        this.usuario = usuario;
    }

}
