/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.padaria.view;

import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author W
 */
public class View_Autenticar_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form View_Autenticar_Usuario
     */
    public View_Autenticar_Usuario() {
        initComponents();
        
    }

    private void iniciar(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Senha = new javax.swing.JLabel();
        tf_Senha = new javax.swing.JPasswordField();
        tf_usuário = new javax.swing.JTextField();
        lbl_usuario = new javax.swing.JLabel();
        btn_enviar = new javax.swing.JButton();
        btn_criar_conta = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Senha.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lbl_Senha.setText("Senha");
        getContentPane().add(lbl_Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));
        getContentPane().add(tf_Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 240, 30));

        tf_usuário.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf_usuário.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usuárioActionPerformed(evt);
            }
        });
        getContentPane().add(tf_usuário, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 240, 30));

        lbl_usuario.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lbl_usuario.setText("Usuário");
        getContentPane().add(lbl_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        btn_enviar.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btn_enviar.setText("Enviar");
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 240, 30));

        btn_criar_conta.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btn_criar_conta.setText("Criar Conta");
        getContentPane().add(btn_criar_conta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 240, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Ainda não tem uma conta?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 170, 20));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/padaria/imagens/VIEW_LOGIN_ofc.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_usuárioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usuárioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usuárioActionPerformed

    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_enviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Autenticar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Autenticar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Autenticar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Autenticar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Autenticar_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JToggleButton btn_criar_conta;
    private javax.swing.JButton btn_enviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_Senha;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JPasswordField tf_Senha;
    private javax.swing.JTextField tf_usuário;
    // End of variables declaration//GEN-END:variables

    public JToggleButton getBtn_criar_conta() {
        return btn_criar_conta;
    }

    public void setBtn_criar_conta(JToggleButton btn_criar_conta) {
        this.btn_criar_conta = btn_criar_conta;
    }

    public JButton getBtn_enviar() {
        return btn_enviar;
    }

    public void setBtn_enviar(JButton btn_enviar) {
        this.btn_enviar = btn_enviar;
    }

    public JPasswordField getTf_Senha() {
        return tf_Senha;
    }

    public void setTf_Senha(JPasswordField tf_Senha) {
        this.tf_Senha = tf_Senha;
    }

    public JTextField getTf_usuário() {
        return tf_usuário;
    }

    public void setTf_usuário(JTextField tf_usuário) {
        this.tf_usuário = tf_usuário;
    }


}

